USE [master]
GO

/****** Object:  Database [system]    Script Date: 21/04/2021 9:11:36 AM ******/
CREATE DATABASE [system]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'system', FILENAME = N'C:\Users\Panget mo\system.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'system_log', FILENAME = N'C:\Users\Panget mo\system_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [system].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [system] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [system] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [system] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [system] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [system] SET ARITHABORT OFF 
GO

ALTER DATABASE [system] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [system] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [system] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [system] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [system] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [system] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [system] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [system] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [system] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [system] SET  DISABLE_BROKER 
GO

ALTER DATABASE [system] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [system] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [system] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [system] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [system] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [system] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [system] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [system] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [system] SET  MULTI_USER 
GO

ALTER DATABASE [system] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [system] SET DB_CHAINING OFF 
GO

ALTER DATABASE [system] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [system] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [system] SET  READ_WRITE 
GO

